name: Deploy
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 'latest'
      - name: Install dependencies
        run: bun  install --no-frozen-lockfile
      - name: Build
        run: bun  run build
      - name: Ls
        run: ls -al dist
      - name: Depoly
        uses: kostya-ten/ssh-server-deploy@v4
        with:
          host: ${{ secrets.VPS_ADDR }}
          port: ${{ secrets.VPS_PORT }}
          username: ${{ secrets.VPS_USR }}
          private_key: ${{ secrets.VPS_KEY }}
          scp_source: 'dist/*'
          scp_target: '/home/aolose/errApp/'
          after_script: |
            cd "/home/aolose/errApp/"  && bun i && echo -e "${{ secrets.VPS_PWD }}\n" | sudo -S service errApp restart
